#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: matmul

# STEP: vivado_flow
cd /home/cindy/hls-dse
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /home/cindy/hls-dse/HLS_output//Synthesis/vivado_flow/vivado.tcl


