#!/bin/bash
ulimit -s 131072
cd /home/cindy/hls-dse
(cd /home/cindy/hls-dse/panda-temp//temp-archive-dir-7255-70f3-0004-f73c; ar x /tmp/.mount_bambuzJLO97/usr/lib/panda/libhls-cdiv_gcc49.a)  > /home/cindy/hls-dse/panda-temp/shell_output_2 2>&1 
