#!/bin/bash
ulimit -s 131072
cd /home/cindy/hls-dse
(cd /home/cindy/hls-dse/panda-temp//temp-archive-dir-fd97-337e-4819-4dd4; ar x /tmp/.mount_bambuzJLO97/usr/lib/panda/libhls-divnr1_gcc49.a)  > /home/cindy/hls-dse/panda-temp/shell_output_4 2>&1 
